from pathlib import Path
WRAPPER = (Path(workflow.basedir) / 'pvl/aggregate').as_uri()
rule all:
    input: 'snakemake-result'
rule aggregate:
    input:
        counts=config.get('input', 'counts.h5ad'),
        settings=config.get('settings', 'settings.json')
    output: directory('snakemake-result')
    log: 'aggregate.log'
    threads: 1
    resources: mem_mb=1024
    wrapper: WRAPPER
